<?php

return array(
	array(
		'name' => 'popup_show_on_toggle',
		'title' => __('Show Popup', 'mantra-audience'),
		'description' => "",
		'type' => "radio",
		'enable_toggle' => true,
		'meta' => array(
			array('value' => 'all-pages', 'name' => __('Entire Site', 'mantra-audience'), 'selected' => true),
			array('value' => 'specific-pages', 'name' => __('Specific Pages','mantra-audience')),
		),
		'default' => 'all-pages',
	),
	array(
		'name' 		=> 'popup_show',
		'title' 	=> '',
		'description' => '',
		'type' 		=> 'assignments',
		'exclude_post_types' => array( 'mantra_audience' ),
		'toggle' => array( 'specific-pages-toggle' ),
	),
	array(
		'name' => 'popup_show_to',
		'title' => 'Guests or Logged-in',
		'type' => 'dropdown',
		'meta' => array(
			array( 'value' => '', 'name' => __( 'Show to both users and guest visitors', 'mantra-audience' ) ),
			array( 'value' => 'guest', 'name' => __( 'Show only to guest visitors', 'mantra-audience' ) ),
			array( 'value' => 'user', 'name' => __( 'Show only to logged-in users', 'mantra-audience' ) ),
		),
		'default' => '',
	),
	array(
		'name' 		=> 'popup_no_date_limit',
		'title' 	=> __('Schedule Popup', 'mantra-audience'),
		'description' => '',
		'type' 		=> 'checkbox',
	),
	array(
		'name' 		=> 'popup_start_at',
		'title' 	=> __('Start at', 'mantra-audience'),
		'description' => '',
		'type' 		=> 'date',
		'meta'		=> array(
			'default' => '',
			'pick' => __( 'Pick Date', 'mantra-audience' ),
			'close' => __( 'Done', 'mantra-audience' ),
			'clear' => __( 'Clear Date', 'mantra-audience' ),
			'time_format' => 'HH:mm:ss',
			'date_format' => 'yy-mm-dd',
			'timeseparator' => ' ',
			'required' => true
		),
	),
	array(
		'name' 		=> 'popup_end_at',
		'title' 	=> __('End at', 'mantra-audience'),
		'description' => __('Start and End Date fields are required', 'mantra-audience'),
		'type' 		=> 'date',
		'meta'		=> array(
			'default' => '',
			'pick' => __( 'Pick Date', 'mantra-audience' ),
			'close' => __( 'Done', 'mantra-audience' ),
			'clear' => __( 'Clear Date', 'mantra-audience' ),
			'time_format' => 'HH:mm:ss',
			'date_format' => 'yy-mm-dd',
			'timeseparator' => ' ',
			'required' => true
		)
	),
	array(
		'name' => 'popup_trigger',
		'title' => __('Trigger Popup', 'mantra-audience'),
		'description' => "",
		'type' => "radio",
		'enable_toggle' => true,
		'meta' => array(
			array('value' => 'timedelay', 'name' => __('Time Delay','mantra-audience'), 'selected' => true),
			array('value' => 'exit', 'name' => __('Exit Intent','mantra-audience')),
			array('value' => 'default', 'name' => __('Page Viewed','mantra-audience')),
			array('value' => 'scroll', 'name' => __('Scroll Position','mantra-audience')),
			array('value' => 'manual', 'name' => __('Manual Launch','mantra-audience')),
		),
		'default_selected' => '',
		'default' => 'timedelay',
	),
	array(
		'name' => 'popup_manual_description',
		'type' => 'post_id_info',
		'description' => __( 'To insert manual launch popup button, use the Popup generator button on WordPress visual editor.', 'mantra-audience' ),
		'toggle' => array( 'manual-toggle' ),
		'title' => '&nbsp;',
	),
	array(
		'name' => 'popup_trigger_time_delay',
		'title' => __('Time Delay', 'mantra-audience'),
		'description' => '',
		'type' => 'textbox',
		'meta' => array('size' => 'small'),
		'before' => '',
		'after' => __(' Seconds', 'mantra-audience'),
		'toggle' => array( 'timedelay-toggle' ),
		'default' => 5
	),
	array(
		'type' => 'multi',
		'name' => 'popup_scroll_position',
		'title' => __('Scroll Position', 'mantra-audience'),
		'meta' => array(
			'fields' => array(
				array(
					'name' => 'popup_trigger_scroll_position',
					'title' => __('Scroll Position', 'mantra-audience'),
					'description' => '',
					'type' => 'textbox',
					'meta' => array('size' => 'small'),
				),
				array(
					'name' => 'popup_trigger_scroll_on',
					'title' => '',
					'type' => 'dropdown',
					'meta' => array(
						array( 'value' => 'px', 'name' => __( 'Pixels', 'mantra-audience' ) ),
						array( 'value' => '%', 'name' => __( 'Percentage of screen', 'mantra-audience' ) ),
					),
					'default' => 'px',
				),
			),
			'before' => '',
			'after' => '',
			'separator' => ''
		),
		'toggle' => array( 'scroll-toggle' )
	),
	array(
		'name' => 'popup_style',
		'title' => __('Popup Style', 'mantra-audience'),
		'description' => "",
		'type' => "radio",
		'enable_toggle' => true,
		'meta' => array(
			array('value' => 'classic', 'name' => __('Classic','mantra-audience'), 'selected' => true),
			array('value' => 'slide-out', 'name' => __('Slide Out','mantra-audience')),
			array('value' => 'fullscreen', 'name' => __('Fullscreen','mantra-audience')),
		),
		'default_selected' => '',
		'default' => 'classic',
	),
	array(
		'name' => 'popup_slide_out_position',
		'title' => __( 'Position', 'mantra-audience' ),
		'type' => 'dropdown',
		'meta' => array(
			array( 'value' => 'bottom-right', 'name' => __( 'Bottom Right', 'mantra-audience' ) ),
			array( 'value' => 'bottom-left', 'name' => __( 'Bottom Left', 'mantra-audience' ) ),
			array( 'value' => 'bottom-center', 'name' => __( 'Bottom Center', 'mantra-audience' ) ),
			array( 'value' => 'top-right', 'name' => __( 'Top Right', 'mantra-audience' ) ),
			array( 'value' => 'top-left', 'name' => __( 'Top Left', 'mantra-audience' ) ),
			array( 'value' => 'top-center', 'name' => __( 'Top Center', 'mantra-audience' ) ),
			array( 'value' => 'center-right', 'name' => __( 'Centered Right', 'mantra-audience' ) ),
			array( 'value' => 'center-left', 'name' => __( 'Centered Left', 'mantra-audience' ) ),
		),
		'toggle' => array( 'slide-out-toggle' ),
		'default' => 'bottom-right',
	),
	array(
		'name' => 'popup_classic_position',
		'title' => __( 'Position', 'mantra-audience' ),
		'type' => 'dropdown',
		'meta' => array(
			array( 'value' => 'center-center', 'name' => __( 'Center', 'mantra-audience' ) ),
			array( 'value' => 'bottom-right', 'name' => __( 'Bottom Right', 'mantra-audience' ) ),
			array( 'value' => 'bottom-left', 'name' => __( 'Bottom Left', 'mantra-audience' ) ),
			array( 'value' => 'bottom-center', 'name' => __( 'Bottom Center', 'mantra-audience' ) ),
			array( 'value' => 'top-right', 'name' => __( 'Top Right', 'mantra-audience' ) ),
			array( 'value' => 'top-left', 'name' => __( 'Top Left', 'mantra-audience' ) ),
			array( 'value' => 'top-center', 'name' => __( 'Top Center', 'mantra-audience' ) ),
			array( 'value' => 'center-right', 'name' => __( 'Centered Right', 'mantra-audience' ) ),
			array( 'value' => 'center-left', 'name' => __( 'Centered Left', 'mantra-audience' ) ),
		),
		'toggle' => array( 'classic-toggle' ),
		'default' => 'center-center',
	),
	array(
		'type' => 'multi',
		'name' => 'popup_dimensions',
		'title' => __('Popup Dimension', 'mantra-audience'),
		'meta' => array(
			'fields' => array(
				array(
					'name' => 'popup_width',
					'label' => __('width', 'mantra-audience'),
					'description' => '',
					'type' => 'textbox',
					'meta' => array('size' => 'small'),
                    'default' => '500',

                ),
				array(
					'name' => 'popup_width_unit',
					'title' => '',
					'type' => 'dropdown',
					'meta' => array(
						array( 'value' => 'px', 'name' => __( 'px', 'mantra-audience' ) ),
						array( 'value' => '%', 'name' => __( '%', 'mantra-audience' ) ),
						array( 'value' => 'em', 'name' => __( 'em', 'mantra-audience' ) ),
					),
					'default' => 'px',
					'after' => '<br>',
				),
				array(
					'name' 		=> 'popup_auto_height',
					'title' 	=> '',
					'label' 	=> __('Auto Height', 'mantra-audience'),
					'description' => '',
					'type' 		=> 'checkbox',
					'after' => '<br>',
				),
				array(
					'name' => 'popup_height',
					'label' => __('height', 'mantra-audience'),
					'type' => 'textbox',
					'meta' => array( 'size' => 'small' )
				),
				array(
					'name' => 'popup_height_unit',
					'title' => '',
					'type' => 'dropdown',
					'meta' => array(
						array( 'value' => 'px', 'name' => __( 'px', 'mantra-audience' ) ),
						array( 'value' => '%', 'name' => __( '%', 'mantra-audience' ) ),
					),
					'default' => 'px',
				),
			),
			'before' => '',
			'after' => '',
			'separator' => ''
		),
		'toggle' => array( 'classic-toggle', 'slide-out-toggle' )
	),
	array(
		'name' => 'popup_overlay_color',
		'title' => __('Overlay Color', 'announcement-bar'),
		'description' => '',
		'type' => 'color',
		'meta' => array( 'default' => null ),
		'toggle' => array( 'classic-toggle' ),
		'format' => 'rgba',
	),
	array(
		'name' => 'popup_animation',
		'title' => __( 'Open Animation', 'mantra-audience' ),
		'type' => 'dropdown',
		'meta' => array(
			array( 'value' => 'bounce', 'name' => __( 'bounce', 'mantra-audience' ) ),
			array( 'value' => 'flash', 'name' => __( 'flash', 'mantra-audience' ) ),
			array( 'value' => 'pulse', 'name' => __( 'pulse', 'mantra-audience' ) ),
			array( 'value' => 'rubberBand', 'name' => __( 'rubberBand', 'mantra-audience' ) ),
			array( 'value' => 'shake', 'name' => __( 'shake', 'mantra-audience' ) ),
			array( 'value' => 'swing', 'name' => __( 'swing', 'mantra-audience' ) ),
			array( 'value' => 'tada', 'name' => __( 'tada', 'mantra-audience' ) ),
			array( 'value' => 'wobble', 'name' => __( 'wobble', 'mantra-audience' ) ),
			array( 'value' => 'jello', 'name' => __( 'jello', 'mantra-audience' ) ),
			array( 'value' => 'bounceIn', 'name' => __( 'bounceIn', 'mantra-audience' ) ),
			array( 'value' => 'bounceInDown', 'name' => __( 'bounceInDown', 'mantra-audience' ) ),
			array( 'value' => 'bounceInLeft', 'name' => __( 'bounceInLeft', 'mantra-audience' ) ),
			array( 'value' => 'bounceInRight', 'name' => __( 'bounceInRight', 'mantra-audience' ) ),
			array( 'value' => 'bounceInUp', 'name' => __( 'bounceInUp', 'mantra-audience' ) ),
			array( 'value' => 'fadeIn', 'name' => __( 'fadeIn', 'mantra-audience' ) ),
			array( 'value' => 'fadeInDown', 'name' => __( 'fadeInDown', 'mantra-audience' ) ),
			array( 'value' => 'fadeInDownBig', 'name' => __( 'fadeInDownBig', 'mantra-audience' ) ),
			array( 'value' => 'fadeInLeft', 'name' => __( 'fadeInLeft', 'mantra-audience' ) ),
			array( 'value' => 'fadeInLeftBig', 'name' => __( 'fadeInLeftBig', 'mantra-audience' ) ),
			array( 'value' => 'fadeInRight', 'name' => __( 'fadeInRight', 'mantra-audience' ) ),
			array( 'value' => 'fadeInRightBig', 'name' => __( 'fadeInRightBig', 'mantra-audience' ) ),
			array( 'value' => 'fadeInUp', 'name' => __( 'fadeInUp', 'mantra-audience' ) ),
			array( 'value' => 'fadeInUpBig', 'name' => __( 'fadeInUpBig', 'mantra-audience' ) ),
			array('value' => 'lightSpeedIn', 'name' => __('lightSpeedIn', 'mantra-audience')),
			array('value' => 'lightSpeedOut', 'name' => __('lightSpeedOut', 'mantra-audience')),
			array('value' => 'rotateIn', 'name' => __('rotateIn', 'mantra-audience')),
			array('value' => 'rotateInDownLeft', 'name' => __('rotateInDownLeft', 'mantra-audience')),
			array('value' => 'rotateInDownRight', 'name' => __('rotateInDownRight', 'mantra-audience')),
			array('value' => 'rotateInUpLeft', 'name' => __('rotateInUpLeft', 'mantra-audience')),
			array('value' => 'rotateInUpRight', 'name' => __('rotateInUpRight', 'mantra-audience')),
			array('value' => 'zoomIn', 'name' => __('zoomIn', 'mantra-audience')),
			array('value' => 'zoomInDown', 'name' => __('zoomInDown', 'mantra-audience')),
			array('value' => 'zoomInLeft', 'name' => __('zoomInLeft', 'mantra-audience')),
			array('value' => 'zoomInRight', 'name' => __('zoomInRight', 'mantra-audience')),
			array('value' => 'zoomInUp', 'name' => __('zoomInUp', 'mantra-audience')),
			array('value' => 'slideInDown', 'name' => __('slideInDown', 'mantra-audience')),
			array('value' => 'slideInLeft', 'name' => __('slideInLeft', 'mantra-audience')),
			array('value' => 'slideInRight', 'name' => __('slideInRight', 'mantra-audience')),
			array('value' => 'slideInUp', 'name' => __('slideInUp', 'mantra-audience')),
		),
		'default' => 'bounce'
	),
	array(
		'name' => 'popup_animation_exit',
		'title' => __( 'Exit Animation', 'mantra-audience' ),
		'type' => 'dropdown',
		'meta' => array(
			array( 'value' => 'fadeOut', 'name' => __( 'fadeOut', 'mantra-audience' ) ),
			array( 'value' => 'fadeOutDown', 'name' => __( 'fadeOutDown', 'mantra-audience' ) ),
			array( 'value' => 'fadeOutDownBig', 'name' => __( 'fadeOutDownBig', 'mantra-audience' ) ),
			array( 'value' => 'fadeOutLeft', 'name' => __( 'fadeOutLeft', 'mantra-audience' ) ),
			array( 'value' => 'fadeOutLeftBig', 'name' => __( 'fadeOutLeftBig', 'mantra-audience' ) ),
			array( 'value' => 'fadeOutRight', 'name' => __( 'fadeOutRight', 'mantra-audience' ) ),
			array( 'value' => 'fadeOutRightBig', 'name' => __( 'fadeOutRightBig', 'mantra-audience' ) ),
			array( 'value' => 'fadeOutUp', 'name' => __( 'fadeOutUp', 'mantra-audience' ) ),
			array( 'value' => 'fadeOutUpBig', 'name' => __( 'fadeOutUpBig', 'mantra-audience' ) ),
			array( 'value' => 'bounceOut', 'name' => __( 'bounceOut', 'mantra-audience' ) ),
			array( 'value' => 'bounceOutDown', 'name' => __( 'bounceOutDown', 'mantra-audience' ) ),
			array( 'value' => 'bounceOutLeft', 'name' => __( 'bounceOutLeft', 'mantra-audience' ) ),
			array( 'value' => 'bounceOutRight', 'name' => __( 'bounceOutRight', 'mantra-audience' ) ),
			array( 'value' => 'bounceOutUp', 'name' => __( 'bounceOutUp', 'mantra-audience' ) ),
			array( 'value' => 'lightSpeedOut', 'name' => __( 'lightSpeedOut', 'mantra-audience' ) ),
			array( 'value' => 'rotateOut', 'name' => __( 'rotateOut', 'mantra-audience' ) ),
			array( 'value' => 'rotateOutDownLeft', 'name' => __( 'rotateOutDownLeft', 'mantra-audience' ) ),
			array( 'value' => 'rotateOutDownRight', 'name' => __( 'rotateOutDownRight', 'mantra-audience' ) ),
			array( 'value' => 'rotateOutUpLeft', 'name' => __( 'rotateOutUpLeft', 'mantra-audience' ) ),
			array( 'value' => 'rotateOutUpRight', 'name' => __( 'rotateOutUpRight', 'mantra-audience' ) ),
			array( 'value' => 'slideOutUp', 'name' => __( 'slideOutUp', 'mantra-audience' ) ),
			array( 'value' => 'slideOutDown', 'name' => __( 'slideOutDown', 'mantra-audience' ) ),
			array( 'value' => 'slideOutLeft', 'name' => __( 'slideOutLeft', 'mantra-audience' ) ),
			array( 'value' => 'slideOutRight', 'name' => __( 'slideOutRight', 'mantra-audience' ) ),
			array( 'value' => 'zoomOut', 'name' => __( 'zoomOut', 'mantra-audience' ) ),
			array( 'value' => 'zoomOutDown', 'name' => __( 'zoomOutDown', 'mantra-audience' ) ),
			array( 'value' => 'zoomOutLeft', 'name' => __( 'zoomOutLeft', 'mantra-audience' ) ),
			array( 'value' => 'zoomOutRight', 'name' => __( 'zoomOutRight', 'mantra-audience' ) ),
			array( 'value' => 'zoomOutUp', 'name' => __( 'zoomOutUp', 'mantra-audience' ) ),
			array( 'value' => 'rollOut', 'name' => __( 'rollOut', 'mantra-audience' ) ),
		),
		'default' => 'fadeOut'
	),
	array(
		'name' 		=> 'popup_limit_count',
		'title' 	=> __( 'Limit display', 'mantra-audience' ),
		'label' 	=> '&nbsp;',
		'before' => __( 'Show the popup only ', 'mantra-audience' ),
		'after' => __( ' times.', 'mantra-audience' ),
		'type' 		=> 'textbox',
		'meta' => array('size' => 'small')
	),
	array(
		'name' => 'popup_cookie_expiration',
		'title' => '',
		'before' => __('Reset the counter after ', 'mantra-audience'),
		'after' => __( ' days.', 'mantra-audience' ),
		'type' => 'textbox',
		'meta' => array('size' => 'small')
	),
	array(
		'name' => 'popup_page_view',
		'title' => __('Page Count', 'mantra-audience'),
		'after' => __( ' Display popup only after [n] page views.', 'mantra-audience' ),
		'type' => 'textbox',
		'meta' => array( 'size' => 'small' ),
	),
	array(
		'name' 		=> 'popup_auto_close',
		'title' 	=> __('Auto Close', 'mantra-audience'),
		'label' => __('Auto close popup', 'mantra-audience'),
		'description' => '',
		'type' 		=> 'checkbox',
	),
	array(
		'name' => 'popup_auto_close_delay',
		'title' => '',
		'before' => __('Close popup after ', 'mantra-audience'),
		'after' => __( ' Seconds', 'mantra-audience' ),
		'type' => 'textbox',
		'meta' => array('size' => 'small'),
		'default' => 5
	),
	array(
		'name' 		=> 'popup_mobile_disable',
		'title' 	=> __('Mobile Disable', 'mantra-audience'),
		'label' => __('Disable popup on mobile', 'mantra-audience'),
		'description' => '',
		'type' 		=> 'checkbox',
	),
	array(
		'name' 		=> 'popup_overlay_as_close',
		'title' 	=> __('Overlay As Close', 'mantra-audience'),
		'label' => __('Allow clicking the popup overlay to close', 'mantra-audience'),
		'description' => '',
		'type' 		=> 'checkbox',
		'toggle' => array( 'classic-toggle' )
	),
);